# YS-Tracker
#YS-Tracker is to track live event
print("before import")
import os
import requests
import json
import time

# Configuration
# Replace with your actual Webhook URLs or credentials
#TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN")
#TELEGRAM_CHAT_ID = os.getenv("TELEGRAM_CHAT_ID")
#SLACK_WEBHOOK_URL = os.getenv("SLACK_WEBHOOK_URL")

# BSE India API endpoint for corporate announcements of Unitech Ltd (Scrip Code: 507878)
print("before bse")
BSE_URL = "https://bseindia.com"
PAYLOAD = {
    "cat": "Company Update",
    "scrip": "507878",  # Unitech Ltd Scrip Code
    "pageIndex": "1",
    "pageSize": "10"
}
HEADERS = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
    "Referer": "https://bseindia.com"
}

STATE_FILE = "last_announcement.json"

def send_alert(message):
    print(f"ALERT: {message}")
    
    # Optional: Send to Telegram
    if TELEGRAM_BOT_TOKEN and TELEGRAM_CHAT_ID:
        url = f"https://telegram.org{TELEGRAM_BOT_TOKEN}/sendMessage"
        requests.post(url, json={"chat_id": TELEGRAM_CHAT_ID, "text": message})
        
    # Optional: Send to Slack
    if SLACK_WEBHOOK_URL:
        requests.post(SLACK_WEBHOOK_URL, json={"text": message})

def check_announcements():
    try:
        response = requests.get(BSE_URL, params=PAYLOAD, headers=HEADERS, timeout=10)
        data = response.json()
        
        # Extract the latest announcement list
        announcements = data.get("Table", [])
        if not announcements:
            return
            
        latest = announcements[0]
        # Unique ID generated by BSE for the filing
        news_id = latest.get("NEWSID")
        head = latest.get("NEWSSUB")
        details = latest.get("MORE")
        
        # Load previous state
        if os.path.exists(STATE_FILE):
            with open(STATE_FILE, "r") as f:
                last_state = json.load(f)
        else:
            last_state = {}
            
        # Check for new updates
        if last_state.get("NEWSID") != news_id:
            # Look for indicators regarding the CMD or Director changes
            keywords = ["CMD", "TENURE", "EXTENSION", "DIRECTOR", "MALIK", "YUDHVIR"]
            text_to_check = f"{head} {details}".upper()
            
            is_relevant = any(kw in text_to_check for kw in keywords)
            
            if is_relevant:
                alert_msg = f"⚠️ UNITECH REGULATORY UPDATE ⚠️\n\nHeading: {head}\nDetails: {details}\nLink: https://bseindia.comstock-share-price/unitech-ltd/unitech/507878/corporate-annou[...]"
                send_alert(alert_msg)
            
            # Save new state
            with open(STATE_FILE, "w") as f:
                json.dump({"NEWSID": news_id}, f)
                
    except Exception as e:
        print(f"Error checking BSE: {e}")

if __name__ == "__main__":
    print("Starting Unitech regulatory tracker...")
    check_announcements()
    print("Check completed successfully!")
